#!/usr/bin/env bash
# Installs ngnix, listens on port 80, modifies the default web file, configures redirect_me
apt-get -y update
apt-get -y install nginx
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | tee /var/www/html/custom_404.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/lammyprime permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
service nginx restart
