#!/usr/bin/env bash
# while and if-else statements part2
i="1"
while [ $i -lt 101 ]
do
	if [ $((i % 5)) -eq 0 ] && [ $((i % 3)) -eq 0 ]
	then
	echo "FizzBuzz"
	elif [ $((i % 5)) -eq 0 ]
	then
	echo "Buzz"
	elif [ $((i % 3)) -eq 0 ]
	then
	echo "Fizz"
	else
	echo "$i"
	fi
i=$((i+1))
done
